device: &device 'cuda'
seed: &seed 0

main:
  bounds_min: &bounds_min [-1000, -1000, -1000] #[-0.45, -0.75, 0.698]
  bounds_max: &bounds_max [+1000, +1000, +1000]


keypoint_proposer:
  num_candidates_per_mask: 4
  min_dist_bt_keypoints: 0.06
  max_mask_ratio: 0.7
  min_mask_pixels: 6
  device: *device
  bounds_min: *bounds_min
  bounds_max: *bounds_max
  seed: *seed